### ISSUE TITLE
wpackagist-plugin/cart-rest-api-for-woocommerce version issue

### ISSUE THREAD

**Issue by amman20** [outlandishideas/wpackagist#365] opened 2020-12-01 10:35 UTC
I just refreshed this repo to pull new versions of that plugin.
"wpackagist-plugin/cart-rest-api-for-woocommerce":"2.7.4"

When I tried to installed it via composer I got this weird error.
`Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Root composer.json requires wpackagist-plugin/cart-rest-api-for-woocommerce ^2.7.4, found wpackagist-plugin/cart-rest-api-for-woocommerce[dev-trunk, 2.4.0, ..., 2.7.0] but it does not match the constraint.`

[Plugin Link](https://wpackagist.org/search?q=cart-rest-api-for-woocommerce)

Any idea why?

**Comment by cfaria** [comment] 2020-12-04 08:08
See #350 

TL;DR After clicking on the refresh icon you have to wait a few hours for the package to be rebuild and reflect the new version.

**Comment by NoelLH** [comment] 2020-12-22 09:35
Thanks for the report. As you've identified, I'm closing this as a dupe of known issue #350 so we can keep updates in one place, and have just added details of the specific bug #368 which is the current root issue blocking a fix release. Pull requests are welcome.

**Closed by NoelLH** 2020-12-22 09:35 UTC
