### ISSUE TITLE
wpackagist-plugin/polldaddy doesn't exist as 2.2.1 

### ISSUE THREAD

**Issue by IfElseRun** [outlandishideas/wpackagist#367] opened 2020-12-11 15:50 UTC
When i refreshed wpackagist-plugin/polldaddy it showed 2.2.1 but when  I am trying to update it does not show the version.

**Comment by NoelLH** [comment] 2020-12-22 09:35
Thanks for the report. I'm closing this as a dupe of known issue #350 so we can keep updates in one place, and have just added details of the specific bug #368 which is the current root issue blocking a fix release. Pull requests are welcome.

**Closed by NoelLH** 2020-12-22 09:35 UTC
