### ISSUE TITLE
 [Composer\Downloader\TransportException] - 404 on specific package json

### ISSUE THREAD

**Issue by KRMcGuire** [outlandishideas/wpackagist#382] opened 2021-01-26 18:24 UTC
When I attempt to install the "advanced-custom-fields-table-field" via wpackagist, I get the following error message:

[Composer\Downloader\TransportException]                                                                                                                                                                 
  The "https://wpackagist.org/p/wpackagist-plugin/advanced-custom-fields-table-field%24151602dfd96c576769e853629d3b5242c00057b6270a079007b62ef2f3fc8def.json" file could not be downloaded (HTTP/1.1 404   
  Not Found)          

I'm not encountering this issue with any other packages, from wpackagist or otherwise.

Tested on Composer 1.7.3 and 2.0.8

**Comment by fschroiff** [comment] 2021-02-02 12:34
Duplicate of https://github.com/outlandishideas/wpackagist/issues/381

**Closed** 2021-02-03 10:22 UTC
Labels: duplicate
