### ISSUE TITLE
Current version of rest-api not available on wpackagist

### ISSUE THREAD

**Issue by clovepod** [outlandishideas/wpackagist#180] opened 2016-08-26 14:04 UTC
The current version of the rest-api plugin on wordpress.org is 2.0beta13.1:
https://wordpress.org/plugins/rest-api/changelog/

However, the most recent version available on wpackagist is 2.0beta13:
https://wpackagist.org/search?q=rest-api&type=any&search=

This point release has been out for 3 months.

**Comment by tamlyn** [comment] 2016-08-26 14:16
Duplicate of #164

**Closed by tamlyn** 2016-08-26 14:16 UTC
