### ISSUE TITLE
Can't download plugin advanced-custom-fields-table-field

### ISSUE THREAD

**Issue by robmeijerink** [outlandishideas/wpackagist#383] opened 2021-01-27 09:19 UTC
When trying to install another dependency with Composer. It gives me this error:

  [Composer\Downloader\TransportException]
  The "https://wpackagist.org/p/wpackagist-plugin/advanced-custom-fields-table-field%24151602dfd96c576769e853629d3b52
  42c00057b6270a079007b62ef2f3fc8def.json" file could not be downloaded (HTTP/2 404 )

It used to work fine. Does anyone know how to fix it? When i remove this dependency from my composer.json, everything works fine.

**Comment by fschroiff** [comment] 2021-02-02 12:34
Duplicate of https://github.com/outlandishideas/wpackagist/issues/381

**Closed** 2021-02-03 10:22 UTC
Labels: duplicate
