### ISSUE TITLE
Composer update: 

### ISSUE THREAD

**Issue by ellecarrier** [outlandishideas/wpackagist#62] opened 2015-01-13 15:57 UTC
Recently I've started receiving the following error on all wpackagist repos when running `composer update`, both in local dev environment and on staging server. 

Everything else, including private repos are being read and updated ok via composer. (A month or so back when I first set this up it was working ok too with the same wpackagist hosted plugins).

```
Problem 1
    - The requested package wpackagist/admin-menu-editor could not be found in any version, there may be a typo in the package name.`

There are 17 of these all reporting the same error, 
And...
```

```
Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
```

So far:
Looking at composer.json its the same as it has always been, searching wpackagist I see the versions are indeed listed. Composer self-update latest, composer validate is showing OK, stability is dev, clearing composer cache makes no difference, and `curl -sS https://getcomposer.org/installer | php -- --check` reports ok.

composer.json is:

```
  "type"        : "project",
  "minimum-stability": "dev",

  "repositories": [
    {
      "type": "composer",
      "url": "http://wpackagist.org"
    }
```
And some of the packages throwing this error

```
"require": {
    "wpackagist/admin-menu-editor": "1.4.*",
    "wpackagist/advanced-access-manager": "2.8.*",
    "wpackagist/dvk-social-sharing": "1.2.*",
    "wpackagist/enable-media-replace": "3.*",    
    "wpackagist/ewww-image-optimizer": "2.0.*",     
    "wpackagist/genesis-layout-extras": "2.0.*"
  }
```
Any ideas?!

Best wishes
Sean

**Comment by lavoiesl** [comment] 2015-01-13 16:01
Duplicate of #60

**Closed by lavoiesl** 2015-01-13 16:01 UTC
Labels: duplicate, invalid
