### ISSUE TITLE
"wpackagist-plugin/pta-volunteer-sign-up-sheets":"3.4.0"

### ISSUE THREAD

**Issue by vbengeult** [outlandishideas/wpackagist#347] opened 2020-10-07 17:22 UTC
This package is visible on wordpress.org but "composer require wpackagist-plugin/pta-volunteer-sign-up-sheets" returns 404 Not Found error.

**Comment by NoelLH** [comment] 2020-12-22 09:42
Thanks for the report. I see versions on Wpackagist.org now so am closing this as a likely dupe of known issue #350 so we can keep updates in one place, and have just added details of the specific bug #368 which is the current root issue blocking a fix release. Pull requests are welcome.

Please reopen with more info if there is a distinct ongoing issue and I'm missing something.

**Closed by NoelLH** 2020-12-22 09:42 UTC
