### ISSUE TITLE
Not new plugin version

### ISSUE THREAD

**Issue by elmervoors** [outlandishideas/wpackagist#352] opened 2020-10-27 09:30 UTC
The plugin wp-image-zoooom have a new version 1.44 only on wpackagist is the version 1.43. This plugin is update a month ago

**Comment by VlooMan** [comment] 2020-10-27 11:32
Hi, I figured out that you have to manually refresh the repo. Then wait an hour or two and it will be available in your CLI.
![image](https://user-images.githubusercontent.com/4932723/97296107-8273a780-1850-11eb-8814-8b180c56c825.png)

**Comment by NoelLH** [comment] 2020-12-22 09:37
Thanks for the report. I'm closing this as a dupe of known issue #350 so we can keep updates in one place, and have just added details of the specific bug #368 which is the current root issue blocking a fix release. Pull requests are welcome.

**Closed by NoelLH** 2020-12-22 09:37 UTC
