### ISSUE TITLE
wp-password-policy-manager could not be found in any version

### ISSUE THREAD

**Issue by rapind** [outlandishideas/wpackagist#85] opened 2015-04-05 02:06 UTC
Looks like it's there according to the site http://wpackagist.org/search?q=wp-password-policy-manager but I get this error regardless of version (even with *).

"The requested package wpackagist-plugin/wp-password-policy-manager could not be found in any version, there may be a typo in the package name."

**Comment by lavoiesl** [comment] 2015-04-05 02:06
Most probably a duplicate of #84

**Comment by rapind** [comment] 2015-04-05 02:08
Yes sorry, it is probably the same root cause, but I reported it separately because it might require an additional action (updating of files).

**Comment by lavoiesl** [comment] 2015-04-05 02:10
Let’s close this one in favour of the other and reopen if needed.

**Closed by lavoiesl** 2015-04-05 02:10 UTC
