### ISSUE TITLE
geodirectory is several versions behind

### ISSUE THREAD

**Issue by penhtech** [outlandishideas/wpackagist#360] opened 2020-11-21 11:12 UTC
The current version of geodirectory on wordpress.org is 2.1.0.5 but nothing newer than 2.0.0.101 is on wpackagist.

**Comment by NoelLH** [comment] 2020-12-22 09:38
Thanks for the report. I'm closing this as a dupe of known issue #350 so we can keep updates in one place, and have just added details of the specific bug #368 which is the current root issue blocking a fix release. Pull requests are welcome.

**Closed by NoelLH** 2020-12-22 09:38 UTC
