### ISSUE TITLE
wpackagist.org no longer fetching latest updates from WP

### ISSUE THREAD

**Issue by allen-mcnichols** [outlandishideas/wpackagist#318] opened 2020-08-27 17:40 UTC
Having to manually refresh the plugins I need to run updates for in order to install and update them with Composer.

**Comment by dear-leader** [comment] 2020-08-29 10:05
I'm experiencing the same issue. Any updates?

**Comment by handpressed** [comment] 2020-08-30 09:57
I noticed my fork had also stopped updating — something to do with the WP API returning 404s for discontinued plugins and themes. I updated to the GitHub pull request from June — [https://github.com/outlandishideas/wpackagist/pull/314](https://github.com/outlandishideas/wpackagist/pull/314) — which fixed it. My fork is public: [https://wpackagist.handpressed.net](https://wpackagist.handpressed.net)

**Comment by NoelLH** [comment] 2020-08-30 21:28
Thanks for spotting that link @handpressed and deploying the branch. I think the framework change PR with that fix is about ready to merge, but we've been busy and trying to sort out a hopefully-future-proof infrastructure change to get it deployed while moving to the latest PHP. That's coming along with use on another project, and hopefully we'll get Wpackagist moved over in the next couple of weeks.

**Comment by strarsis** [comment] 2020-09-05 15:18
I can confirm for some plugins (TI Wishlist Plugin). When the plugin is manually refreshed, the new version is shown immediately in the search results. But composer cannot find it when updating to that new version, even after waiting 10 Minutes.

**Comment by allen-mcnichols** [comment] 2020-09-06 06:06
It takes about an hour for the refreshed plugin to show up via composer. So far performing an update has been a matter of check the admin for updates, go through my composer list and see which plugins are in my composer.json for wpackagist, search for each plugin, refresh, wait an hour, update via composer and go on with my day. Makes for a long update process but it does eventually show up.

**Comment by NoelLH** [comment] 2020-09-06 11:23
Thanks @allen-mcnichols, I suspected that may be the case. I think there is a job which runs every couple of minutes which is supposed to pick up queued updates, which I suspect isn't working as intended, and one that runs hourly which is.

When we get to rolling out the update and new infrastructure I'll try to work out what's going on and if all else fails try to find a way to increase the frequency of the full updates.

**Comment by timnolte** [comment] 2020-09-14 18:46
This issue is seriously hampering development work that is dependent on the latest release of a plugin. I've refreshed the plugin on wpackist.org and it's showing the new version number but no number of `composer clear-cache` & `composer update ...` is working. This is a real big pain.

**Comment by NoelLH** [comment] 2020-09-14 22:08
Hi @timnolte, I have had time only to get as far as deploying untested staging implementation of the new, significantly refactored codebase. Please feel free to try the untested https://staging-wpackagist.out.re/ and let me know how you get on. I'll be having a closer look at whether it's actually working as expected when time allows.

**Comment by timnolte** [comment] 2020-09-14 22:10
> Hi @timnolte, I have had time only to get as far as deploying untested staging implementation of the new, significantly refactored codebase. Please feel free to try the untested https://staging-wpackagist.out.re/ in place of the normal repo domain and let me know how you get on. I'll be having a closer look at whether it's actually working as expected when time allows.

Thanks @NoelLH

**Comment by hphoeksma** [comment] 2020-09-17 12:23
> Hi @timnolte, I have had time only to get as far as deploying untested staging implementation of the new, significantly refactored codebase. Please feel free to try the untested https://staging-wpackagist.out.re/ in place of the normal repo domain and let me know how you get on. I'll be having a closer look at whether it's actually working as expected when time allows.

Hi @NoelLH - when trying this url instead of the normal domain, composer throws me a not found error:
`The "https://staging-wpackagist.out.re/packages.json" file could not be downloaded (HTTP/1.1 404 Not Found)`

**Comment by NoelLH** [comment] 2020-09-18 12:19
@hphoeksma thanks, that was a pretty big oversight! I carefully put the SQLite database in a shared location to support horizontal scaling, but forgot the output files that are the whole point of the process..

[Fixed now](https://github.com/outlandishideas/wpackagist/pull/325), hopefully.

**Comment by hphoeksma** [comment] 2020-09-18 12:53
@NoelLH - yes, working fine now :-) Thanks!

**Comment by abdusfauzi** [comment] 2020-09-19 01:16
@NoelLH i visited the staging site, and tried to manually update after I search `storefront`, and this error pops up. Just letting you know.

Thanks for the hard work 👍 

<img width="1920" alt="Screenshot 2020-09-19 at 09 15 04" src="https://user-images.githubusercontent.com/1118229/93655842-b8a35780-fa58-11ea-82c1-9f267de00963.png">

**Comment by strarsis** [comment] 2020-09-19 06:54
Will the staging site replace the current wpackagist site when everything is done?

**Comment by NoelLH** [comment] 2020-09-19 09:13
@strarsis yes. I'm hoping to switch it over Monday if no critical issues.

@abdusfauzi thanks, that should be resolved now.

**Comment by abdusfauzi** [comment] 2020-09-19 09:14
@NoelLH awesome

**Comment by NoelLH** [comment] 2020-09-22 07:28
Thanks for the comments everyone, I'm not delighted with the update performance but everything seems to work now, so I have just switched over Production to the updated codebase with more secure libraries etc.

For now, package updates that involve brand new releases may take up to ~11 minutes from when you press the button to trigger an 'early' refresh. Please create new issues for any specific cases that don't seem to be behaving like this. I'll try to monitor through this week and may consider re-thinking the overlapping task schedules if the current setup proves annoying / too slow.

**Closed by NoelLH** 2020-09-22 07:28 UTC
