### ISSUE TITLE
widget-google-reviews outdated

### ISSUE THREAD

**Issue by sozomartin** [outlandishideas/wpackagist#397] opened 2021-03-03 12:25 UTC
version 1.9.3 is available wordpress.org but there has not been any fetched since 1.4.3

**Comment by sozomartin** [comment] 2021-03-03 12:41
Just a side note, this is actually due to the developers tagging earlier versions 1.49 for example incorrectly so using **"wpackagist-plugin/widget-google-reviews": "~1",** it won't actually fetch the latest version.

**Comment by NoelLH** [comment] 2021-03-26 11:51
Thanks for investigating and confirming the cause @sozomartin. I don't really see a way Wpackagist could deal with this case systematically and distinguish it from correct/intentional use of higher semver feature version numbers, so will close this for now.

I think the best fix is for the package maintainer to unpublish any problematic versions. Hopefully in the mean time you can work around the publishing issue by pinning to the specific 'real' latest patch version in `composer.json`.

Please let me know if you think there's something Wpackagist could/should do in this case.

**Closed by NoelLH** 2021-03-26 11:51 UTC
Labels: upstream-packaging
