### ISSUE TITLE
blog2social 6.5.1 not found

### ISSUE THREAD

**Issue by jamieburchell** [outlandishideas/wpackagist#346] opened 2020-10-05 23:00 UTC
The blog2social plugin (https://wordpress.org/plugins/blog2social/#description) exists at version 6.5.1 but is not found when using composer:

```
Problem 1
    - The requested package wpackagist-plugin/blog2social 6.5.1 exists as wpackagist-plugin/blog2social[3.1.3, 3.7.0, 3.7.1, 4.0.0, 4.1.0, 4.1.1, 4.2.0, 4.2.1, 4.2.2, 4.3.0, 4.3.1, 4.3.2, 4.3.3, 4.4.0, 4.4.1, 4.5.0, 4.5.1, 4.6.0, 4.7.0, 4.8.0, 4.8.1, 4.8.2, 4.8.3, 4.9.0, 4.9.1, 4.9.2, 5.0.0, 5.0.1, 5.0.2, 5.0.3, 5.0.4, 5.1.0, 5.1.1, 5.1.2, 5.1.3, 5.1.4, 5.2.0, 5.3.0, 5.4.0, 5.4.1, 5.5.0, 5.6.0, 5.6.1, 5.7.0, 5.7.1, 5.7.2, 5.8.0, 5.8.1, 5.9.0, 6.0.0, 6.1.0, 6.1.1, 6.1.2, 6.2.0, 6.3.0, 6.3.1, 6.4.0, 6.4.1, 6.4.2, dev-trunk] but these are rejected by your constraint.
```

It does appear on wpackagist though:

https://wpackagist.org/search?q=blog2social&type=any&search=

> dev-trunk ... 6.4.2 6.5.0 6.5.1

And in the WP SVN repo:

https://plugins.svn.wordpress.org/blog2social/tags/6.5.1/

**Comment by khromov** [comment] 2020-10-05 23:16
Closing as duplicate of https://github.com/outlandishideas/wpackagist/issues/345

**Closed by khromov** 2020-10-05 23:16 UTC

**Comment by jamieburchell** [comment] 2020-10-05 23:33
Apologies for the duplicate post; for some reason I got a GitHub 404 page the first time I submitted this.
