### ISSUE TITLE
google-maps-widget not showing latest version from 4 weeks ago

### ISSUE THREAD

**Issue by penhtech** [outlandishideas/wpackagist#355] opened 2020-11-08 12:35 UTC
wpackagist-plugin/google-maps-widget is not showing version 4.19, which was released 4  weeks ago: https://wordpress.org/plugins/google-maps-widget/

**Comment by NoelLH** [comment] 2020-12-22 09:37
Thanks for the report. I'm closing this as a dupe of known issue #350 so we can keep updates in one place, and have just added details of the specific bug #368 which is the current root issue blocking a fix release. Pull requests are welcome.

**Closed by NoelLH** 2020-12-22 09:37 UTC
