### ISSUE TITLE
Peer certificate CN=`wpackagist.out.re' did not match expe     cted CN=`wpackagist.org'

### ISSUE THREAD

**Issue by strarsis** [outlandishideas/wpackagist#274] opened 2018-05-18 11:19 UTC
@tamlyn, @lavoiesl, @benlumley, @tonypiper, @scribu, @conatus:
````
The "https://wpackagist.org/packages.json" file could not be downloaded: Peer certificate CN=`wpackagist.out.re' did not match expected CN=`wpackagist.org'
Failed to enable crypto
failed to open stream: operation failed
https://wpackagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date
````

````
[Composer\Downloader\TransportException]
The "https://wpackagist.org/p/wpackagist-plugin/jquery-smooth-scroll%240138ead848400c53d9d150ca600e450fe8ef0b3f920e     b6ae4743460f43db85ca.json" file could not be downloaded: Peer certificate CN=`wpackagist.out.re' did not match expected CN=`wpackagist.org'
Failed to enable crypto
failed to open stream: operation failed
````

Same error when vistiing [](https://wpackagist.org/) in browser (Chrome):
````
NET::ERR_CERT_COMMON_NAME_INVALID
````
The certificate comes from `wpackagist.out.re` instead.

https://www.ssllabs.com/ssltest/analyze.html?d=wpackagist.org&hideResults=on&latest

**Comment by joaquimds** [comment] 2018-05-18 11:25
Hopefully it's fixed now. We were moving servers.

**Comment by josephfusco** [comment] 2018-05-18 11:29
Confirmed fixed for me. Thank you!

**Comment by josephfusco** [comment] 2018-05-18 11:32
Now I am getting the following from the 3 wpackagist plugins I have.

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package wpackagist-theme/twentyseventeen could not be found in any version, there may be a typo in the package name.
  Problem 2
    - The requested package wpackagist-plugin/query-monitor could not be found in any version, there may be a typo in the package name.
  Problem 3
    - The requested package wpackagist-plugin/wordpress-importer could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it
```

**Comment by JockeTF** [comment] 2018-05-18 11:51
Same here. It seems none of our plug-ins can be resolved.

**Comment by JockeTF** [comment] 2018-05-18 11:55
Works again now, thank you!

**Closed** 2018-05-18 11:57 UTC

**Comment by josephfusco** [comment] 2018-05-18 12:29
Confirmed works for me too. Thanks!
