### ISSUE TITLE
Package not found 

### ISSUE THREAD

**Issue by lhoucinecherif** [outlandishideas/wpackagist#364] opened 2020-11-26 00:27 UTC
Could not find package wpackagist-plugin/loginpress in a version matching 1.5.0

**Comment by NoelLH** [comment] 2020-12-22 09:36
Thanks for the report. I'm closing this as a dupe of known issue #350 so we can keep updates in one place, and have just added details of the specific bug #368 which is the current root issue blocking a fix release. Pull requests are welcome.

**Closed by NoelLH** 2020-12-22 09:36 UTC
