### ISSUE TITLE
Man in the middle just with wpackagist.com

### ISSUE THREAD

**Issue by TCattd** [outlandishideas/wpackagist#67] opened 2015-02-13 15:16 UTC
I'm posting this here, because this error just shows up then i'm trying to use wpackagist.org with composer.
I tested my problem with Laravel before posting here.
Just installed a fresh Laravel copy, using composer, and use another old 4.2 Laravel installation too, and running composer update on both runs without a problem. All updated.

But fails when try to run composer update in a WP install that was working before using composer and wpackagist.
My last commit using composer update to the proyect we use wpackagist was from was from 4 days ago (9th february).

Now it doesn't work:
```
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)



  [Composer\Repository\RepositorySecurityException]
  The contents of http://wpackagist.org/p/providers-2012$04faa1dfb29949500ecdc35870e20aed1fd76d2a
  5e6a7e0572233f2d0d3cc951.json do not match its signature. This should indicate a man-in-the-mid
  dle attack. Try running composer again and report this if you think it is a mistake.



update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [packages1] ... [packagesN]
```

This is a verbose update:
```
$ composer update -v
Loading composer repositories with package information
Updating dependencies (including require-dev)



  [Composer\Repository\RepositorySecurityException]
  The contents of http://wpackagist.org/p/providers-2012$04faa1dfb29949500ecdc35870e20aed1fd76d2a
  5e6a7e0572233f2d0d3cc951.json do not match its signature. This should indicate a man-in-the-mid
  dle attack. Try running composer again and report this if you think it is a mistake.



Exception trace:
 () at phar:///usr/local/bin/composer/src/Composer/Repository/ComposerRepository.php:596
 Composer\Repository\ComposerRepository->fetchFile() at phar:///usr/local/bin/composer/src/Composer/Repository/ComposerRepository.php:494
 Composer\Repository\ComposerRepository->loadProviderListings() at phar:///usr/local/bin/composer/src/Composer/Repository/ComposerRepository.php:265
 Composer\Repository\ComposerRepository->whatProvides() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Pool.php:187
 Composer\DependencyResolver\Pool->computeWhatProvides() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Pool.php:176
 Composer\DependencyResolver\Pool->whatProvides() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/RuleSetGenerator.php:168
 Composer\DependencyResolver\RuleSetGenerator->whitelistFromPackage() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/RuleSetGenerator.php:322
 Composer\DependencyResolver\RuleSetGenerator->getRulesFor() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Solver.php:171
 Composer\DependencyResolver\Solver->solve() at phar:///usr/local/bin/composer/src/Composer/Installer.php:503
 Composer\Installer->doInstall() at phar:///usr/local/bin/composer/src/Composer/Installer.php:225
 Composer\Installer->run() at phar:///usr/local/bin/composer/src/Composer/Command/UpdateCommand.php:140
 Composer\Command\UpdateCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:252
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:874
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:146
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:83
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:43
 require() at /usr/local/bin/composer:25


update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [packages1] ... [packagesN]
```
I setup a new WP install, a new composer.json and some plugins in there to just test, and i get the same error.

I even reinstall composer from scratch (removing the .phar and .composer completly from my home).

BTW, this is using OSX Mavericks.

I'm trying to solve this from yesterday, reading a lot from others with the man-in-the-middle error, but with no luck at all.

Please, some help.

**Comment by lavoiesl** [comment] 2015-02-13 18:10
This can be because you download fails midway, potentially due to partial or crashed downloads. This can also be because the content is indeed modified.

Try manually downloading the file and inspecting its content to see if it is truncated.

Try also manually checking its checksum:
```bash
wget 'http://wpackagist.org/p/providers-2012$04faa1dfb29949500ecdc35870e20aed1fd76d2a5e6a7e0572233f2d0d3cc951.json'
shasum -a 256 'http://wpackagist.org/p/providers-2012$04faa1dfb29949500ecdc35870e20aed1fd76d2a5e6a7e0572233f2d0d3cc951.json'
```

If this is all ok, try clearing your `~/.composer/cache` folder.

**Comment by TCattd** [comment] 2015-02-13 18:25
404 :/

```
$ wget 'http://wpackagist.org/p/providers-2012$04faa1dfb29949500ecdc35870e20aed1fd76d2a5e6a7e0572233f2d0d3cc951.json'
--2015-02-13 15:24:14--  http://wpackagist.org/p/providers-2012$04faa1dfb29949500ecdc35870e20aed1fd76d2a5e6a7e0572233f2d0d3cc951.json
Resolving wpackagist.org... 212.13.212.63
Connecting to wpackagist.org|212.13.212.63|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-02-13 15:24:15 ERROR 404: Not Found.
```

**Comment by lavoiesl** [comment] 2015-02-13 18:26
Of course, packages are always changing. Grab yourself a fresh one from http://wpackagist.org/packages.json

**Comment by TCattd** [comment] 2015-02-13 18:30
Same, using the hashes i see at that json:

http://i.imgur.com/sWAhdtl.png

Tested 2015 and 2012 hashes. No luck. 404 both.

**Comment by lavoiesl** [comment] 2015-02-13 18:31
You need 'quotes' like in my examples, otherwise, the $ gets evaluated.

**Comment by TCattd** [comment] 2015-02-13 18:35
Sorry, my bad.

I can get one without problems.
Tested with 2014, and my local shasum matches the one i see at http://wpackagist.org/packages.json

```
bb841bdf1f845c251d9cbb0f0e36ef92b8b1100e7f478e4074868eba22a2a1ca
```

**Comment by lavoiesl** [comment] 2015-02-13 18:37
And if you clear your `~/.composer/cache` you still have the problem? No timeout errors, etc? I don’t know man, sorry. 

Try from another computer perhaps?

**Comment by TCattd** [comment] 2015-02-13 18:43
Now works :/
I don't get it.

I didn't clear my ~/.composer/cache/ folder.
As i said before, i already nuked and reinstalled composer a couple of times actually. That includes removing ~/.composer/ completely. But after that composer was still complaning, just for wpackagist.org

And now it works.
Don't know what happen.

Almost two days trying to figure it out, and now that you are trying to help, this thing decided to work.

---

Sorry for the troubles, and thanks @lavoiesl for trying to help me. Really.

**Comment by TCattd** [comment] 2015-02-20 00:57
Sorry to bother again, but this problem came back for me... again, and just with wpackagist, not "traditional" packages (tested with laravel, again).

I already do the same checks. Clearing composer cache. Nuked composer completly and reinstalled from zero. Downloaded a provider json and verifying sha on them. Etc.
Nothing. Same issue.

Now, i think it might be something about my ISP, but it just happens with wpackagist.org
I just tether with my phone (now that i faced the very same issue), phone with a different internet data provider, and composer update passed without a single problem.

Does anyone have an idea of why this is happening to me?
Please.

**Comment by lavoiesl** [comment] 2015-02-20 14:35
When you have the issue, try testing the shasum like I showed you, but directly on the cached file located in `~/.composer/cache/repo/`. To know exactly which file, run `composer update -vvv`. Compare that file to the one downloaded using `wget` and perhaps to a `diff` on them. Cheers

**Comment by TCattd** [comment] 2015-02-20 19:58
composer update -vvv

```
Reading ./composer.json
Loading config file ./composer.json
Executing command (CWD): git describe --exact-match --tags
Executing command (CWD): git branch --no-color --no-abbrev -v
Failed to initialize global composer: Composer could not find the config file: /Users/esteban/.composer/composer.json
To initialize a project, please create a composer.json file as described in the http://getcomposer.org/ "Getting Started" section
Loading composer repositories with package information
Downloading http://wpackagist.org/packages.json
Writing /Users/esteban/.composer/cache/repo/http---wpackagist.org/packages.json into cache
Downloading https://packagist.org/packages.json
Writing /Users/esteban/.composer/cache/repo/https---packagist.org/packages.json into cache
Updating dependencies (including require-dev)
Reading /Users/esteban/.composer/cache/repo/http---wpackagist.org/p-providers-2015-03.json from cache
Reading /Users/esteban/.composer/cache/repo/http---wpackagist.org/p-providers-2013.json from cache
Downloading http://wpackagist.org/p/providers-2012$65a4c88c1d456f71e153d7e1d4891168b81c4be4fe2bec22279295e7e87fd732.json
Downloading http://wpackagist.org/p/providers-2012$65a4c88c1d456f71e153d7e1d4891168b81c4be4fe2bec22279295e7e87fd732.json
Downloading http://wpackagist.org/p/providers-2012$65a4c88c1d456f71e153d7e1d4891168b81c4be4fe2bec22279295e7e87fd732.json



  [Composer\Repository\RepositorySecurityException]
  The contents of http://wpackagist.org/p/providers-2012$65a4c88c1d456f71e153d7e1d4891168b81c4be4fe2bec2227929
  5e7e87fd732.json do not match its signature. This should indicate a man-in-the-middle attack. Try running co
  mposer again and report this if you think it is a mistake.



Exception trace:
 () at phar:///usr/local/bin/composer/src/Composer/Repository/ComposerRepository.php:596
 Composer\Repository\ComposerRepository->fetchFile() at phar:///usr/local/bin/composer/src/Composer/Repository/ComposerRepository.php:494
 Composer\Repository\ComposerRepository->loadProviderListings() at phar:///usr/local/bin/composer/src/Composer/Repository/ComposerRepository.php:265
 Composer\Repository\ComposerRepository->whatProvides() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Pool.php:187
 Composer\DependencyResolver\Pool->computeWhatProvides() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Pool.php:176
 Composer\DependencyResolver\Pool->whatProvides() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/RuleSetGenerator.php:161
 Composer\DependencyResolver\RuleSetGenerator->whitelistFromPackage() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/RuleSetGenerator.php:322
 Composer\DependencyResolver\RuleSetGenerator->getRulesFor() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Solver.php:172
 Composer\DependencyResolver\Solver->solve() at phar:///usr/local/bin/composer/src/Composer/Installer.php:504
 Composer\Installer->doInstall() at phar:///usr/local/bin/composer/src/Composer/Installer.php:226
 Composer\Installer->run() at phar:///usr/local/bin/composer/src/Composer/Command/UpdateCommand.php:140
 Composer\Command\UpdateCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:252
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:874
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:146
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:83
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:43
 require() at /usr/local/bin/composer:25


update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [packages1] ... [packagesN]
```

Composer cache shasum
```
attd-zen:http---wpackagist.org esteban$ ll
total 1024
drwxr-xr-x 5 esteban staff    170 Feb 20 16:54 ./
drwxr-xr-x 4 esteban staff    136 Feb 19 21:37 ../
-rw-r--r-- 1 esteban staff 646615 Feb 20 16:54 p-providers-2013.json
-rw-r--r-- 1 esteban staff 394242 Feb 20 16:54 p-providers-2015-03.json
-rw-r--r-- 1 esteban staff    859 Feb 20 16:53 packages.json
attd-zen:http---wpackagist.org esteban$ shasum -a 256 'p-providers-2013.json'
f2e552d31d4180476e808c81515dec2d0c17b89c1f53892deaace2f301db4662  p-providers-2013.json
attd-zen:http---wpackagist.org esteban$ shasum -a 256 'p-providers-2015-03.json'
773ea784347656b8393abc36547f8d7631678e2ae1c4d966fbc12e9d6e1cda6d  p-providers-2015-03.json
attd-zen:http---wpackagist.org esteban$
```

And what i see at http://wpackagist.org/packages.json
```
{
packages: [ ],
providers-url: "/p/%package%$%hash%.json",
provider-includes: {
p/providers-2015-03$%hash%.json: {
sha256: "773ea784347656b8393abc36547f8d7631678e2ae1c4d966fbc12e9d6e1cda6d"
},
p/providers-2013$%hash%.json: {
sha256: "f2e552d31d4180476e808c81515dec2d0c17b89c1f53892deaace2f301db4662"
},
p/providers-2012$%hash%.json: {
sha256: "65a4c88c1d456f71e153d7e1d4891168b81c4be4fe2bec22279295e7e87fd732"
},
p/providers-old$%hash%.json: {
sha256: "d6e2d7714e6b6079122a6923543dfee55ed7b1de5d8bcdc4878f564abc5a6622"
},
p/providers-2011$%hash%.json: {
sha256: "fd83dd39e965524d9512435e405fbc9cd2c8249c092a156694c03d22c2fec95d"
},
p/providers-2014$%hash%.json: {
sha256: "e33d04d5a970ac4c2bd04135ad858343a22900334551eb54c8a7e347d1ce619c"
},
p/providers-this-week$%hash%.json: {
sha256: "c567266b43cea84534097587f7402ac43ed4740caa2a8d73ab59f4b83e4d513d"
}
}
}
```

Already cleared the cache folder, and the same error happens again and again :/

**Comment by lavoiesl** [comment] 2015-02-20 21:14
The file that is giving you the error is the 2012 provider, which is not available in your packagist folder. I should’ve realized that (because it is invalid). I must say, I have no idea :-/

**Comment by TCattd** [comment] 2015-02-20 23:26
I just took my wife Windows machine and tested with it (installed php and composer), just to rule out my machine it's not crazy.

But...
http://i.imgur.com/hKXUbzx.png
http://i.imgur.com/nht5agX.png
http://i.imgur.com/wmmHRFE.png
Same problem, different json (2013 now), but the same problem shows up.

:/

**Comment by lavoiesl** [comment] 2015-02-21 01:23
Try the same laptop, but from a different internet service provider,
another network.

**Comment by TCattd** [comment] 2015-02-22 15:25
As i said before, i already tested doing tethering from my phone, different internet provider, and works.
Other user (friend who help me to test), same ISP but different city in my country, have no problem using wpackagist.org

I just used my regular machine and installed a proxy (Hotspot Shield) to test, and composer updates without an issue:

```
ATTD-Zen:*** esteban$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing wpackagist-plugin/mobile-smart (v1.3.6)
  - Installing wpackagist-plugin/mobile-smart (v1.3.7)
    Downloading: 100%

  - Removing wpackagist-plugin/rvg-optimize-database (3.1)
  - Installing wpackagist-plugin/rvg-optimize-database (3.1.3)
    Downloading: 100%

  - Removing wpackagist-plugin/restrict-usernames (3.4.1)
  - Installing wpackagist-plugin/restrict-usernames (3.5)
    Downloading: 100%

  - Installing wpackagist-plugin/option-tree (2.5.1)
    Downloading: 100%

Writing lock file
Generating autoload files
ATTD-Zen:*** esteban$
```

It works.

So,

Packagist.org uses a "regular" dns provider, anycast, i (and probably many) have no problem with that repository.
But, wpackagist.org uses Cloudflare. And Cloudflare is known by its many features as caching and blocking bot attacks.

(Theory) Cloudflare might be thinking, this by the quick request ratio when updating (asking for multiple json files and very quickly one after another), or because some people with the same ISP as i have could have been trying to attack some domain that uses cloudflare dns too, that my IP range might be trying to DDoS them. So, i think, Cloudflare could be trying to showing me a challenge landing page, but as this (composer update) happens at the terminal, it just simply fails.
This is just a theory, of course.

But i can't test any further, i think.

Someone with access to cloudflare dns control panel can try this out https://support.cloudflare.com/hc/en-us/articles/200171346-How-do-I-block-blacklist-or-trust-whitelist-an-IP-address-manually- ? please.
I could glad give my IP address, I'm sure I'm not a robot.

Please?

**Comment by tamlyn** [comment] 2015-02-23 08:07
Hi Esteban, ping me your IP and I'll have a look. 

Cloudflare isn't yet enabled for the main wpackagist repository. We're just using it as a DNS server which means once it has given you the IP address of our server, the rest of the traffic completely bypasses their network.

Maybe try accessing *with* cloudflare. See #50.

**Comment by TCattd** [comment] 2015-02-23 12:29
@tamlyn thanks, i just sent you an email.

**Comment by tamlyn** [comment] 2015-02-23 14:02
Thanks. I've added your IP to the whitelist. 

Have you tried changing the repository URL to http://**test.**wpackagist.org/ in `composer.json` to use Cloudflare?

    
	"repositories": [
		{
			"type": "composer",
			"url": "http://test.wpackagist.org"
		}
	]

**Comment by TCattd** [comment] 2015-02-23 14:11
Sorry, I had not seen it.

Trying the normal composer update, fails just the same as before. Just tried.

If i change my repository to test.wpackagist.org, works without a problem.

-vvv
```
attd-zen:site-***.cl esteban$ composer update -vvv
Reading ./composer.json
Loading config file ./composer.json
Executing command (CWD): git describe --exact-match --tags
Executing command (CWD): git branch --no-color --no-abbrev -v
Reading /Users/esteban/.composer/composer.json
Loading config file /Users/esteban/.composer/composer.json
Executing command (CWD): git describe --exact-match --tags
Executing command (CWD): git branch --no-color --no-abbrev -v
Loading composer repositories with package information
Downloading http://test.wpackagist.org/packages.json
Writing /Users/esteban/.composer/cache/repo/http---test.wpackagist.org/packages.json into cache
Downloading https://packagist.org/packages.json
Writing /Users/esteban/.composer/cache/repo/https---packagist.org/packages.json into cache
Updating dependencies (including require-dev)
Downloading http://test.wpackagist.org/p/providers-2015-03$ddd3fe21dbfc403c40c0e4511b83963bcc405eacf6405e737068ac163e8009a5.json
Writing /Users/esteban/.composer/cache/repo/http---test.wpackagist.org/p-providers-2015-03.json into cache
Downloading http://test.wpackagist.org/p/providers-2013$2ab052b4ba19fe404a00be2c830b9b01b44ba2e04ee8d49148548d962c874180.json
Writing /Users/esteban/.composer/cache/repo/http---test.wpackagist.org/p-providers-2013.json into cache
Downloading http://test.wpackagist.org/p/providers-2012$efcdd9cf9d0e2839594825631cd4ecba2930750da30ce0c10d61b8885a25fdee.json
Writing /Users/esteban/.composer/cache/repo/http---test.wpackagist.org/p-providers-2012.json into cache
Downloading http://test.wpackagist.org/p/providers-old$738d6265c75697dd7ecdd0cb2d2f17eb30244848c6eb61f75ab50b2e4be2cfc3.json
Writing /Users/esteban/.composer/cache/repo/http---test.wpackagist.org/p-providers-old.json into cache
Downloading http://test.wpackagist.org/p/providers-2011$418fccc9f34a819f1c74f4aa8e82f5b940ac57517eb9508c2cea0826563c7235.json
Writing /Users/esteban/.composer/cache/repo/http---test.wpackagist.org/p-providers-2011.json into cache
Downloading http://test.wpackagist.org/p/providers-2014$28e96d249d965261ca1b1fdf0f891a3b890df516dba49f25bcd12629c9e5cf48.json
Writing /Users/esteban/.composer/cache/repo/http---test.wpackagist.org/p-providers-2014.json into cache
Downloading http://test.wpackagist.org/p/providers-this-week$ff9b90f3ae5098d6cbee5db884541fe57928a4c2466e5e64545ce490c20efefa.json
Writing /Users/esteban/.composer/cache/repo/http---test.wpackagist.org/p-providers-this-week.json into cache
Reading /Users/esteban/.composer/cache/repo/https---packagist.org/p-provider-2013.json from cache
Downloading https://packagist.org/p/provider-2014$f7892df71ec3ef89e2a2a04dcd79a4ba5712d662d4d27ba8cb8013816136b6cc.json
Writing /Users/esteban/.composer/cache/repo/https---packagist.org/p-provider-2014.json into cache
Downloading https://packagist.org/p/provider-2014-04$cd070c6c60c76bcc27d5b51efdcc7d9288968a412f1293aeb1176426ef9ac64f.json
Writing /Users/esteban/.composer/cache/repo/https---packagist.org/p-provider-2014-04.json into cache
Downloading https://packagist.org/p/provider-2014-07$175524b8a2c8bc9e214fbe8f26ab6fbe4b69d4c5f6508efb1d61ca82b7dd8831.json
Writing /Users/esteban/.composer/cache/repo/https---packagist.org/p-provider-2014-07.json into cache
Downloading https://packagist.org/p/provider-2014-10$cffd5db8eb1c0c050c2301cf9a8932bf19fff270a41644e37490aad5c036ab6f.json
Writing /Users/esteban/.composer/cache/repo/https---packagist.org/p-provider-2014-10.json into cache
Downloading https://packagist.org/p/provider-2015-01$8d4db358671e2d243b6b99c5f34dee63c2f9b3bb07015f0dcace335dac1a1bf4.json
Writing /Users/esteban/.composer/cache/repo/https---packagist.org/p-provider-2015-01.json into cache
Reading /Users/esteban/.composer/cache/repo/https---packagist.org/p-provider-archived.json from cache
Downloading https://packagist.org/p/provider-latest$9db4c25bccf20058c07bbb018be6c535c82846412e7bc8e6350c60f554f2c042.json
Writing /Users/esteban/.composer/cache/repo/https---packagist.org/p-provider-latest.json into cache
Reading /Users/esteban/.composer/cache/repo/https---packagist.org/provider-composer$installers.json from cache
Downloading http://test.wpackagist.org/p/wpackagist-plugin/akismet$c4593626d132ef50ce5f37368a05953fbdc561fab9818f1dc818c5b0235d4645.json
```
etc.

Normal...
```
attd-zen:site-***.cl esteban$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing wpackagist-plugin/option-tree (2.5.1)
    Loading from cache

Generating autoload files
attd-zen:site-***.cl esteban$
```

Thanks for that tip.

Really don't know whats happen with the traditional wpackagist.org here with me :/

I tried again changing my ip address with a proxy, and it works without an issue (the main wpackagist.org, without the "test").

**Comment by tamlyn** [comment] 2015-03-09 21:46
I spoke to our server guy who doesn't reckon the problem is at our end. We can see your IP getting `200` responses in our HTTP logs. He also traced your IP and found no blocks or other problems.

I'm closing this issue for now as we have a workaround with CloudFlare even if it's not really resolved.

**Comment by TCattd** [comment] 2015-03-11 13:05
@tamlyn the problem now is that http://test.wpackagist.org/packages.json throws 404

http://prntscr.com/6ff9as

:/

**Comment by tamlyn** [comment] 2015-03-11 13:12
D'oh! Sorry about that. Try again now.

**Comment by TCattd** [comment] 2015-03-11 13:14
Working. Thanks for the quick reply!

**Comment by TCattd** [comment] 2015-03-18 20:35
Sorry to bother @tamlyn , but...
http://test.wpackagist.org/packages.json
http://prntscr.com/6ig08k
404, again.

**Comment by tamlyn** [comment] 2015-03-18 22:22
Ugh, sorry. I know what's wrong. Will fix tomorrow.

**Comment by tamlyn** [comment] 2015-03-19 09:13
OK, fixed again.

**Closed by tamlyn** 2015-03-19 09:13 UTC
Labels: invalid, question

**Comment by TCattd** [comment] 2015-03-19 11:21
Thanks again!
