### ISSUE TITLE
awesome-weather 1.5.11 package ( 8b37df131edd6ea87afbc4c92d69ed360e603197.zip ) is incomplete

### ISSUE THREAD

**Issue by jonathanvanherpe** [outlandishideas/wpackagist#240] opened 2017-06-30 05:53 UTC
Installing the latest awesome-weather results in a zip that only contains 'img' and 'languages' directories. Downloading the zip from wordpress.org results in a zip that does contain all files. I'm not sure if this is a wpackagist bug or wordpress.org issue, but i feel like you might want to know about it.

**Comment by khromov** [comment] 2017-06-30 08:26
This is likely caused by the plugin author making a mistake and then fixing it. Composer still caches the old file if you were unlucky enough to install it during the time that it was broken.

Please run  `composer clear-cache`, delete the plugin from your `wp-content/plugins` folder and run `composer install` again, and you should be good.

**Comment by joaquimds** [comment] 2017-07-28 16:56
@jonathanvanherpe Can I close this issue?

**Comment by jonathanvanherpe** [comment] 2017-09-12 06:24
@joaquimds no, still the same issue, we solved this by reverting to 1.5.10 back then, running composer clear-cache and redownloading it now still gives us this result.

**Comment by khromov** [comment] 2017-12-03 22:30
The latest version of the plugin is available on WPackagist. Please create a new ticket with the contents of your `composer.json` and `composer.lock` if you still have issues with this.

**Closed by khromov** 2017-12-03 22:30 UTC
Labels: missing-plugin
