### ISSUE TITLE
Site not accessible from some users in Guatemala City

### ISSUE THREAD

**Issue by javiertoledos** [outlandishideas/wpackagist#244] opened 2017-07-24 14:41 UTC
I'm trying with a couple of devs in Guatemala to access (and use) wpackagist.org but we're getting connection timeout. We checked with a couple of Latin American friends (Mexico and Nicaragua) and only Guatemala seems to have issues. Is there any regional/IP blocking? 

We have these public IP addresses 186.151.61.230, 186.151.63.226 and 186.151.62.65.

**Comment by joaquimds** [comment] 2017-07-24 15:01
I don't think there is but I will ask the ops guy

**Comment by joaquimds** [comment] 2017-07-24 16:56
@javiertoledos This is the response from ops:

"We do block the odd IP, but that is normally in response to individual trouble. I would guess in this case it could be an ISP blocking access, or not accepting BGP routes, or maybe a client SSL issues (since that server is doing SNI I believe). Can they reach anything else in our range?"

Are you able to reach http://outlandish.com?

**Comment by joaquimds** [comment] 2017-07-24 17:55
@javiertoledos From ops:

"I've popped in a ticket with our upstream carriers.  Certainly the IP ranges
are in blocks (and some of those IPs specifically) that are on various
blacklists (mainly for spam) so it could well be that someone has decided to
not route to their netblocks."

Stay tuned...

**Comment by joaquimds** [comment] 2017-07-24 20:11
@javiertoledos 

"There certainly seems to be an
issue with routing.  It could be our end not accepting a prefix from their
BGP announcements or their end not accepting one of ours.

Should get an answer back from our providers tomorrow hopefully."

**Comment by javiertoledos** [comment] 2017-07-25 01:01
I cannot access http://outlandish.com either. As a workaround we're using a proxy. We tried with other ISP and it worked well. It seems the issue happens only with that particular IP address range. I just wonder if there are other IP ranges or addresses from other countries that are being affected also.

**Comment by joaquimds** [comment] 2017-07-25 09:51
The issue is that Telgua is providing abnormally long routes to your IP
block, which are being filtered out by our service provider (the company
that provides our Web server with an Internet connection).

From ops:

"Our provider is filtering out those long routes in their BGP routers and
is reluctant to increase the length they already accept which (in their
words) is already ridiculous and you have to stop somewhere (these really
long routes eat CPU/RAM which in expensive big Cisco routers is
expensive!).
There really isn’t a need for such long paths.  In essence each element in
a BGP path is a bit like a conventional routing hop (but using Asns, an AS
being what you might think of as an ISP), adding additional prepends
creates more (virtual) hops so a particular route may look less attractive
over another.  So it would allow Telgua to perhaps priorities one upstream
carrier over another.  However it’s quite a coarse way of doing things and
you’d never put in that many unless you wanted the rest of the world to
stop routing traffic to you.
It’s also pretty pointless in reality these days.  All the Tier 1 carriers
(NTT, Layer3, AT&T, Sprint, Telia, etc, etc) peer with each other anyway
(by definition!) and so Tier 3 to 3 paths only ever end up being about 5
elements and even Tier 4 to Tier 4 only about 7.  I’m hoping it’s just
someone who has made a mistake at Telgua, our upstream has emailed them,
but not heard back.  If you have a contact I’d prod them.  I would expect
we are not alone in the world in not being able to access them anymore.
I’d suggest proxying as a way around until their ISP (Telgua) starts being
a bit more sensible."

So it looks like a proxy is the best way to use our services. Sorry for the
inconvenience.

**Comment by joaquimds** [comment] 2017-10-03 11:34
Closing this as it's out of our hands.

**Closed by joaquimds** 2017-10-03 11:34 UTC
Labels: question
