### ISSUE TITLE
Lead Forensics plugin not available

### ISSUE THREAD

**Issue by duff907** [outlandishideas/wpackagist#356] opened 2020-11-09 10:58 UTC
The lead forensics plugin is not available from wpackagist.

Below is a link to the plugin on the wordpress site

https://wordpress.org/plugins/lead-forensics-roi/

**Comment by NoelLH** [comment] 2020-12-22 09:37
Thanks for the report. I'm closing this as a dupe of known issue #350 so we can keep updates in one place, and have just added details of the specific bug #368 which is the current root issue blocking a fix release. Pull requests are welcome.

**Closed by NoelLH** 2020-12-22 09:37 UTC
