### ISSUE TITLE
Add installer for languages

### ISSUE THREAD

**Issue by hason** [outlandishideas/wpackagist#91] opened 2015-05-18 12:47 UTC
https://codex.wordpress.org/Installing_WordPress_in_Your_Language

**Comment by Rarst** [comment] 2015-05-18 14:12
wpackagist doesn't handle WP core in first place? Though managing WP language stuff with Composer is definitely one of lingering issues.

**Comment by tamlyn** [comment] 2015-05-21 14:12
Closing this as needs more info. Please reopen if desired.

**Comment by NoelLH** [comment] 2020-12-22 10:03
I'm going to close this as a dupe of the newer #121 as there is more detailed discussion and alternatives we might take inspiration from on that issue.

**Closed by NoelLH** 2020-12-22 10:03 UTC
Labels: discussion, enhancement
